# Generated by Django 5.2.17 on 2026-10-03 21:52

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bailleur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("physique", "Personne physique"),
                            ("sci_familiale", "SCI familiale"),
                            ("morale", "Personne morale"),
                        ],
                        default="physique",
                        max_length=20,
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=200, verbose_name="nom ou raison sociale"
                    ),
                ),
                (
                    "prenom",
                    models.CharField(blank=True, max_length=100, verbose_name="prénom"),
                ),
                (
                    "ref_ics",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="référence ICS",
                    ),
                ),
                ("adresse", models.CharField(blank=True, max_length=255)),
                (
                    "code_postal",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="code postal"
                    ),
                ),
                ("ville", models.CharField(blank=True, max_length=100)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="téléphone"
                    ),
                ),
                (
                    "siren",
                    models.CharField(blank=True, max_length=14, verbose_name="SIREN"),
                ),
            ],
            options={
                "verbose_name": "bailleur",
                "ordering": ["nom", "prenom"],
            },
        ),
        migrations.CreateModel(
            name="Bien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "ref_ics",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="référence ICS du lot",
                    ),
                ),
                (
                    "usage",
                    models.CharField(
                        choices=[
                            ("habitation", "Habitation"),
                            ("professionnel", "Local professionnel"),
                            ("commercial", "Local commercial"),
                            ("stationnement", "Parking ou garage"),
                        ],
                        default="habitation",
                        max_length=20,
                    ),
                ),
                ("meuble", models.BooleanField(default=False, verbose_name="meublé")),
                (
                    "actif",
                    models.BooleanField(
                        default=True,
                        help_text="Décocher pour un bien qui n'est plus géré par l'agence.",
                    ),
                ),
                ("adresse", models.CharField(max_length=255)),
                (
                    "complement",
                    models.CharField(
                        blank=True,
                        help_text="Bâtiment, escalier, étage, porte.",
                        max_length=255,
                        verbose_name="complément",
                    ),
                ),
                (
                    "code_postal",
                    models.CharField(max_length=10, verbose_name="code postal"),
                ),
                ("ville", models.CharField(max_length=100)),
                (
                    "type_habitat",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("collectif", "Immeuble collectif"),
                            ("individuel", "Individuel"),
                        ],
                        max_length=20,
                        verbose_name="type d'habitat",
                    ),
                ),
                (
                    "regime_juridique",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("copropriete", "Copropriété"),
                            ("monopropriete", "Monopropriété"),
                        ],
                        max_length=20,
                        verbose_name="régime juridique de l'immeuble",
                    ),
                ),
                (
                    "periode_construction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("avant_1949", "Avant 1949"),
                            ("1949_1974", "De 1949 à 1974"),
                            ("1975_1989", "De 1975 à 1989"),
                            ("1990_2005", "De 1990 à 2005"),
                            ("apres_2005", "Depuis 2005"),
                        ],
                        max_length=20,
                        verbose_name="période de construction",
                    ),
                ),
                (
                    "surface",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="surface habitable (m²)",
                    ),
                ),
                (
                    "nb_pieces",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="nombre de pièces principales",
                    ),
                ),
                (
                    "equipements",
                    models.TextField(
                        blank=True, verbose_name="équipements du logement"
                    ),
                ),
                (
                    "chauffage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("individuel", "Individuel"),
                            ("collectif", "Collectif"),
                        ],
                        max_length=20,
                        verbose_name="production de chauffage",
                    ),
                ),
                (
                    "eau_chaude",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("individuel", "Individuel"),
                            ("collectif", "Collectif"),
                        ],
                        max_length=20,
                        verbose_name="production d'eau chaude",
                    ),
                ),
                (
                    "acces_tic",
                    models.CharField(
                        blank=True,
                        help_text="Raccordement fibre, antenne collective…",
                        max_length=255,
                        verbose_name="accès aux technologies de l'information",
                    ),
                ),
                (
                    "annexes",
                    models.TextField(
                        blank=True,
                        help_text="Cave, parking, jardin…",
                        verbose_name="locaux et équipements privatifs",
                    ),
                ),
                (
                    "parties_communes",
                    models.TextField(
                        blank=True, verbose_name="parties et équipements communs"
                    ),
                ),
                (
                    "classe_dpe",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                            ("NS", "Non soumis"),
                        ],
                        max_length=2,
                        verbose_name="classe DPE",
                    ),
                ),
                (
                    "depenses_energie_min",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="dépenses annuelles d'énergie estimées, minimum (€)",
                    ),
                ),
                (
                    "depenses_energie_max",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="dépenses annuelles d'énergie estimées, maximum (€)",
                    ),
                ),
                (
                    "date_dpe",
                    models.DateField(blank=True, null=True, verbose_name="date du DPE"),
                ),
                (
                    "zone_tendue",
                    models.BooleanField(default=False, verbose_name="zone tendue"),
                ),
                (
                    "loyer_reference_majore",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Seulement si la commune applique l'encadrement des loyers.",
                        max_digits=7,
                        null=True,
                        verbose_name="loyer de référence majoré (€/m²)",
                    ),
                ),
                (
                    "dernier_loyer",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=9,
                        null=True,
                        verbose_name="dernier loyer hors charges (€)",
                    ),
                ),
                (
                    "charges",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=9,
                        null=True,
                        verbose_name="provision sur charges (€)",
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                (
                    "bailleur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="biens",
                        to="biens.bailleur",
                    ),
                ),
            ],
            options={
                "verbose_name": "bien",
                "ordering": ["ville", "adresse", "complement"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalBailleur",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="créé le"
                    ),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="modifié le"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("physique", "Personne physique"),
                            ("sci_familiale", "SCI familiale"),
                            ("morale", "Personne morale"),
                        ],
                        default="physique",
                        max_length=20,
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=200, verbose_name="nom ou raison sociale"
                    ),
                ),
                (
                    "prenom",
                    models.CharField(blank=True, max_length=100, verbose_name="prénom"),
                ),
                (
                    "ref_ics",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="référence ICS",
                    ),
                ),
                ("adresse", models.CharField(blank=True, max_length=255)),
                (
                    "code_postal",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="code postal"
                    ),
                ),
                ("ville", models.CharField(blank=True, max_length=100)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="téléphone"
                    ),
                ),
                (
                    "siren",
                    models.CharField(blank=True, max_length=14, verbose_name="SIREN"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical bailleur",
                "verbose_name_plural": "historical bailleurs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalBien",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="créé le"
                    ),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="modifié le"
                    ),
                ),
                (
                    "ref_ics",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="référence ICS du lot",
                    ),
                ),
                (
                    "usage",
                    models.CharField(
                        choices=[
                            ("habitation", "Habitation"),
                            ("professionnel", "Local professionnel"),
                            ("commercial", "Local commercial"),
                            ("stationnement", "Parking ou garage"),
                        ],
                        default="habitation",
                        max_length=20,
                    ),
                ),
                ("meuble", models.BooleanField(default=False, verbose_name="meublé")),
                (
                    "actif",
                    models.BooleanField(
                        default=True,
                        help_text="Décocher pour un bien qui n'est plus géré par l'agence.",
                    ),
                ),
                ("adresse", models.CharField(max_length=255)),
                (
                    "complement",
                    models.CharField(
                        blank=True,
                        help_text="Bâtiment, escalier, étage, porte.",
                        max_length=255,
                        verbose_name="complément",
                    ),
                ),
                (
                    "code_postal",
                    models.CharField(max_length=10, verbose_name="code postal"),
                ),
                ("ville", models.CharField(max_length=100)),
                (
                    "type_habitat",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("collectif", "Immeuble collectif"),
                            ("individuel", "Individuel"),
                        ],
                        max_length=20,
                        verbose_name="type d'habitat",
                    ),
                ),
                (
                    "regime_juridique",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("copropriete", "Copropriété"),
                            ("monopropriete", "Monopropriété"),
                        ],
                        max_length=20,
                        verbose_name="régime juridique de l'immeuble",
                    ),
                ),
                (
                    "periode_construction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("avant_1949", "Avant 1949"),
                            ("1949_1974", "De 1949 à 1974"),
                            ("1975_1989", "De 1975 à 1989"),
                            ("1990_2005", "De 1990 à 2005"),
                            ("apres_2005", "Depuis 2005"),
                        ],
                        max_length=20,
                        verbose_name="période de construction",
                    ),
                ),
                (
                    "surface",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="surface habitable (m²)",
                    ),
                ),
                (
                    "nb_pieces",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="nombre de pièces principales",
                    ),
                ),
                (
                    "equipements",
                    models.TextField(
                        blank=True, verbose_name="équipements du logement"
                    ),
                ),
                (
                    "chauffage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("individuel", "Individuel"),
                            ("collectif", "Collectif"),
                        ],
                        max_length=20,
                        verbose_name="production de chauffage",
                    ),
                ),
                (
                    "eau_chaude",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("individuel", "Individuel"),
                            ("collectif", "Collectif"),
                        ],
                        max_length=20,
                        verbose_name="production d'eau chaude",
                    ),
                ),
                (
                    "acces_tic",
                    models.CharField(
                        blank=True,
                        help_text="Raccordement fibre, antenne collective…",
                        max_length=255,
                        verbose_name="accès aux technologies de l'information",
                    ),
                ),
                (
                    "annexes",
                    models.TextField(
                        blank=True,
                        help_text="Cave, parking, jardin…",
                        verbose_name="locaux et équipements privatifs",
                    ),
                ),
                (
                    "parties_communes",
                    models.TextField(
                        blank=True, verbose_name="parties et équipements communs"
                    ),
                ),
                (
                    "classe_dpe",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                            ("NS", "Non soumis"),
                        ],
                        max_length=2,
                        verbose_name="classe DPE",
                    ),
                ),
                (
                    "depenses_energie_min",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="dépenses annuelles d'énergie estimées, minimum (€)",
                    ),
                ),
                (
                    "depenses_energie_max",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="dépenses annuelles d'énergie estimées, maximum (€)",
                    ),
                ),
                (
                    "date_dpe",
                    models.DateField(blank=True, null=True, verbose_name="date du DPE"),
                ),
                (
                    "zone_tendue",
                    models.BooleanField(default=False, verbose_name="zone tendue"),
                ),
                (
                    "loyer_reference_majore",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Seulement si la commune applique l'encadrement des loyers.",
                        max_digits=7,
                        null=True,
                        verbose_name="loyer de référence majoré (€/m²)",
                    ),
                ),
                (
                    "dernier_loyer",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=9,
                        null=True,
                        verbose_name="dernier loyer hors charges (€)",
                    ),
                ),
                (
                    "charges",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=9,
                        null=True,
                        verbose_name="provision sur charges (€)",
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "bailleur",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biens.bailleur",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical bien",
                "verbose_name_plural": "historical biens",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
