# Generated by Django 5.2.17 on 2026-10-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biens", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bailleur",
            name="civilite",
            field=models.CharField(
                blank=True,
                choices=[("M.", "Monsieur"), ("Mme", "Madame")],
                max_length=5,
                verbose_name="civilité",
            ),
        ),
        migrations.AddField(
            model_name="bailleur",
            name="conjoint_civilite",
            field=models.CharField(
                blank=True,
                choices=[("M.", "Monsieur"), ("Mme", "Madame")],
                max_length=5,
                verbose_name="civilité du conjoint",
            ),
        ),
        migrations.AddField(
            model_name="bailleur",
            name="conjoint_nom",
            field=models.CharField(
                blank=True,
                max_length=200,
                verbose_name="nom du conjoint ou co-propriétaire",
            ),
        ),
        migrations.AddField(
            model_name="bailleur",
            name="conjoint_prenom",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="prénom du conjoint"
            ),
        ),
        migrations.AddField(
            model_name="bien",
            name="detecteur_fumee",
            field=models.BooleanField(
                default=False, verbose_name="détecteur de fumée installé"
            ),
        ),
        migrations.AddField(
            model_name="bien",
            name="dispositif_fiscal",
            field=models.CharField(
                blank=True,
                help_text="Pinel, Denormandie, Loc'Avantages… Le loyer peut alors être plafonné.",
                max_length=200,
                verbose_name="dispositif fiscal et n° de convention",
            ),
        ),
        migrations.AddField(
            model_name="bien",
            name="etage",
            field=models.CharField(blank=True, max_length=20, verbose_name="étage"),
        ),
        migrations.AddField(
            model_name="bien",
            name="numero_appartement",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="n° d'appartement"
            ),
        ),
        migrations.AddField(
            model_name="bien",
            name="numero_cellier",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="n° de cave ou cellier"
            ),
        ),
        migrations.AddField(
            model_name="bien",
            name="numero_parking",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="n° de parking"
            ),
        ),
        migrations.AddField(
            model_name="bien",
            name="syndic",
            field=models.CharField(
                blank=True,
                help_text="Syndic de l'immeuble, si ce n'est pas l'agence.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="historicalbailleur",
            name="civilite",
            field=models.CharField(
                blank=True,
                choices=[("M.", "Monsieur"), ("Mme", "Madame")],
                max_length=5,
                verbose_name="civilité",
            ),
        ),
        migrations.AddField(
            model_name="historicalbailleur",
            name="conjoint_civilite",
            field=models.CharField(
                blank=True,
                choices=[("M.", "Monsieur"), ("Mme", "Madame")],
                max_length=5,
                verbose_name="civilité du conjoint",
            ),
        ),
        migrations.AddField(
            model_name="historicalbailleur",
            name="conjoint_nom",
            field=models.CharField(
                blank=True,
                max_length=200,
                verbose_name="nom du conjoint ou co-propriétaire",
            ),
        ),
        migrations.AddField(
            model_name="historicalbailleur",
            name="conjoint_prenom",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="prénom du conjoint"
            ),
        ),
        migrations.AddField(
            model_name="historicalbien",
            name="detecteur_fumee",
            field=models.BooleanField(
                default=False, verbose_name="détecteur de fumée installé"
            ),
        ),
        migrations.AddField(
            model_name="historicalbien",
            name="dispositif_fiscal",
            field=models.CharField(
                blank=True,
                help_text="Pinel, Denormandie, Loc'Avantages… Le loyer peut alors être plafonné.",
                max_length=200,
                verbose_name="dispositif fiscal et n° de convention",
            ),
        ),
        migrations.AddField(
            model_name="historicalbien",
            name="etage",
            field=models.CharField(blank=True, max_length=20, verbose_name="étage"),
        ),
        migrations.AddField(
            model_name="historicalbien",
            name="numero_appartement",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="n° d'appartement"
            ),
        ),
        migrations.AddField(
            model_name="historicalbien",
            name="numero_cellier",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="n° de cave ou cellier"
            ),
        ),
        migrations.AddField(
            model_name="historicalbien",
            name="numero_parking",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="n° de parking"
            ),
        ),
        migrations.AddField(
            model_name="historicalbien",
            name="syndic",
            field=models.CharField(
                blank=True,
                help_text="Syndic de l'immeuble, si ce n'est pas l'agence.",
                max_length=200,
            ),
        ),
    ]
