# Generated by Django 5.2.17 on 2026-10-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biens", "0002_fiche_logement_et_conjoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="bien",
            name="identifiant_fiscal",
            field=models.CharField(
                blank=True,
                help_text="Visible dans l'espace « Gérer mes biens immobiliers » du propriétaire sur impots.gouv.fr.",
                max_length=20,
                verbose_name="identifiant fiscal du logement",
            ),
        ),
        migrations.AddField(
            model_name="historicalbien",
            name="identifiant_fiscal",
            field=models.CharField(
                blank=True,
                help_text="Visible dans l'espace « Gérer mes biens immobiliers » du propriétaire sur impots.gouv.fr.",
                max_length=20,
                verbose_name="identifiant fiscal du logement",
            ),
        ),
    ]
