# Generated by Django 5.2.17 on 2026-10-03 22:59

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("biens", "0002_fiche_logement_et_conjoint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalMandat",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="créé le"
                    ),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="modifié le"
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="numéro au registre"
                    ),
                ),
                (
                    "mandant",
                    models.CharField(
                        help_text="Tel qu'il apparaîtra en tête du mandat.",
                        max_length=255,
                    ),
                ),
                (
                    "mandant_adresse",
                    models.CharField(max_length=255, verbose_name="adresse du mandant"),
                ),
                (
                    "mandant_code_postal_ville",
                    models.CharField(
                        max_length=120, verbose_name="code postal et ville du mandant"
                    ),
                ),
                (
                    "designation",
                    models.TextField(
                        help_text="Nature, surface, composition.",
                        verbose_name="désignation du bien",
                    ),
                ),
                (
                    "adresse_bien",
                    models.CharField(max_length=255, verbose_name="adresse du bien"),
                ),
                (
                    "loyer_cc",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=9,
                        verbose_name="loyer charges comprises (€)",
                    ),
                ),
                (
                    "charges",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        verbose_name="dont charges (€)",
                    ),
                ),
                (
                    "date_signature",
                    models.DateField(
                        blank=True, null=True, verbose_name="date de signature"
                    ),
                ),
                (
                    "duree_ans",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="durée initiale (ans)"
                    ),
                ),
                (
                    "reconductions",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Nombre de reconductions prévues (0 si aucune).",
                        verbose_name="reconductions tacites",
                    ),
                ),
                (
                    "date_fin",
                    models.DateField(
                        blank=True,
                        help_text="À renseigner à la résiliation ou à l'échéance.",
                        null=True,
                        verbose_name="fin du mandat",
                    ),
                ),
                (
                    "taux_gestion",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("7"),
                        max_digits=5,
                        verbose_name="honoraires de gestion (% TTC)",
                    ),
                ),
                (
                    "base_gestion",
                    models.CharField(
                        choices=[
                            ("encaissements", "Encaissements mensuels"),
                            ("hors_charges", "Encaissements hors charges"),
                            ("charges_comprises", "Encaissements charges comprises"),
                        ],
                        default="charges_comprises",
                        max_length=20,
                        verbose_name="assiette des honoraires",
                    ),
                ),
                (
                    "assurance_loyers_impayes",
                    models.BooleanField(
                        default=False, verbose_name="assurance loyers impayés"
                    ),
                ),
                (
                    "taux_assurance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.90"),
                        max_digits=5,
                        verbose_name="taux de l'assurance (% TTC)",
                    ),
                ),
                (
                    "honoraires_bail_bailleur",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        verbose_name="visite, dossier et bail : part bailleur (€ TTC)",
                    ),
                ),
                (
                    "honoraires_bail_locataire",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        verbose_name="visite, dossier et bail : part locataire (€ TTC)",
                    ),
                ),
                (
                    "honoraires_edl_bailleur",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        verbose_name="état des lieux : part bailleur (€ TTC)",
                    ),
                ),
                (
                    "honoraires_edl_locataire",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        verbose_name="état des lieux : part locataire (€ TTC)",
                    ),
                ),
                (
                    "fichier_signe",
                    models.TextField(
                        blank=True, max_length=100, verbose_name="mandat signé (scan)"
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "bien",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biens.bien",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical mandat de gestion",
                "verbose_name_plural": "historical mandats de gestion",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Mandat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(
                        editable=False, unique=True, verbose_name="numéro au registre"
                    ),
                ),
                (
                    "mandant",
                    models.CharField(
                        help_text="Tel qu'il apparaîtra en tête du mandat.",
                        max_length=255,
                    ),
                ),
                (
                    "mandant_adresse",
                    models.CharField(max_length=255, verbose_name="adresse du mandant"),
                ),
                (
                    "mandant_code_postal_ville",
                    models.CharField(
                        max_length=120, verbose_name="code postal et ville du mandant"
                    ),
                ),
                (
                    "designation",
                    models.TextField(
                        help_text="Nature, surface, composition.",
                        verbose_name="désignation du bien",
                    ),
                ),
                (
                    "adresse_bien",
                    models.CharField(max_length=255, verbose_name="adresse du bien"),
                ),
                (
                    "loyer_cc",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=9,
                        verbose_name="loyer charges comprises (€)",
                    ),
                ),
                (
                    "charges",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        verbose_name="dont charges (€)",
                    ),
                ),
                (
                    "date_signature",
                    models.DateField(
                        blank=True, null=True, verbose_name="date de signature"
                    ),
                ),
                (
                    "duree_ans",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="durée initiale (ans)"
                    ),
                ),
                (
                    "reconductions",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Nombre de reconductions prévues (0 si aucune).",
                        verbose_name="reconductions tacites",
                    ),
                ),
                (
                    "date_fin",
                    models.DateField(
                        blank=True,
                        help_text="À renseigner à la résiliation ou à l'échéance.",
                        null=True,
                        verbose_name="fin du mandat",
                    ),
                ),
                (
                    "taux_gestion",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("7"),
                        max_digits=5,
                        verbose_name="honoraires de gestion (% TTC)",
                    ),
                ),
                (
                    "base_gestion",
                    models.CharField(
                        choices=[
                            ("encaissements", "Encaissements mensuels"),
                            ("hors_charges", "Encaissements hors charges"),
                            ("charges_comprises", "Encaissements charges comprises"),
                        ],
                        default="charges_comprises",
                        max_length=20,
                        verbose_name="assiette des honoraires",
                    ),
                ),
                (
                    "assurance_loyers_impayes",
                    models.BooleanField(
                        default=False, verbose_name="assurance loyers impayés"
                    ),
                ),
                (
                    "taux_assurance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.90"),
                        max_digits=5,
                        verbose_name="taux de l'assurance (% TTC)",
                    ),
                ),
                (
                    "honoraires_bail_bailleur",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        verbose_name="visite, dossier et bail : part bailleur (€ TTC)",
                    ),
                ),
                (
                    "honoraires_bail_locataire",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        verbose_name="visite, dossier et bail : part locataire (€ TTC)",
                    ),
                ),
                (
                    "honoraires_edl_bailleur",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        verbose_name="état des lieux : part bailleur (€ TTC)",
                    ),
                ),
                (
                    "honoraires_edl_locataire",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        verbose_name="état des lieux : part locataire (€ TTC)",
                    ),
                ),
                (
                    "fichier_signe",
                    models.FileField(
                        blank=True,
                        upload_to="mandats/",
                        verbose_name="mandat signé (scan)",
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                (
                    "bien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mandats",
                        to="biens.bien",
                    ),
                ),
            ],
            options={
                "verbose_name": "mandat de gestion",
                "verbose_name_plural": "mandats de gestion",
                "ordering": ["-numero"],
            },
        ),
    ]
