# Generated by Django 5.2.17 on 2026-10-04 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Modele",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=60, unique=True)),
                (
                    "lien_google",
                    models.URLField(
                        blank=True, max_length=300, verbose_name="lien du Google Doc"
                    ),
                ),
                (
                    "origine",
                    models.CharField(
                        choices=[
                            ("origine", "Modèle d'origine"),
                            ("depot", "Fichier Word déposé"),
                            ("google", "Repris de Google Docs"),
                            ("precedent", "Version précédente remise en service"),
                        ],
                        default="origine",
                        max_length=10,
                    ),
                ),
                (
                    "mis_en_service_le",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="mis en service le"
                    ),
                ),
                (
                    "mis_en_service_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="mis en service par",
                    ),
                ),
            ],
            options={
                "verbose_name": "modèle",
            },
        ),
    ]
