# Generated by Django 5.2.17 on 2026-10-03 23:21

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("biens", "0003_identifiant_fiscal"),
        ("mandats", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("nu", "Logement nu"),
                            ("meuble", "Logement meublé"),
                            ("etudiant", "Logement meublé loué à un étudiant (9 mois)"),
                        ],
                        default="nu",
                        max_length=10,
                        verbose_name="type de bail",
                    ),
                ),
                (
                    "usage_mixte",
                    models.BooleanField(
                        default=False,
                        verbose_name="usage mixte professionnel et d'habitation",
                    ),
                ),
                (
                    "garant",
                    models.CharField(
                        blank=True,
                        help_text="Nom et adresse de la caution, le cas échéant.",
                        max_length=255,
                    ),
                ),
                ("date_effet", models.DateField(verbose_name="date de prise d'effet")),
                (
                    "loyer",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=9,
                        verbose_name="loyer mensuel hors charges (€)",
                    ),
                ),
                (
                    "mode_charges",
                    models.CharField(
                        choices=[
                            (
                                "provision",
                                "Provisions sur charges avec régularisation annuelle",
                            ),
                            ("forfait", "Forfait de charges"),
                        ],
                        default="provision",
                        max_length=10,
                        verbose_name="modalité des charges",
                    ),
                ),
                (
                    "charges",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        verbose_name="provision ou forfait de charges mensuel (€)",
                    ),
                ),
                (
                    "jour_paiement",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="jour de paiement"
                    ),
                ),
                (
                    "a_echoir",
                    models.BooleanField(
                        default=True, verbose_name="payable d'avance (à échoir)"
                    ),
                ),
                (
                    "depot_garantie",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        verbose_name="dépôt de garantie (€)",
                    ),
                ),
                (
                    "irl_trimestre",
                    models.CharField(
                        help_text="Par exemple « 2e trimestre 2026 ».",
                        max_length=30,
                        verbose_name="trimestre de référence de l'IRL",
                    ),
                ),
                (
                    "irl_valeur",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="valeur de l'IRL"
                    ),
                ),
                (
                    "precedent_loyer",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="À renseigner si le précédent locataire est parti depuis moins de 18 mois.",
                        max_digits=9,
                        null=True,
                        verbose_name="dernier loyer du précédent locataire (€)",
                    ),
                ),
                (
                    "precedent_date_versement",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="date de son dernier versement",
                    ),
                ),
                (
                    "precedent_date_revision",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="date de sa dernière révision",
                    ),
                ),
                (
                    "travaux",
                    models.TextField(
                        blank=True,
                        help_text="Montant et nature des travaux d'amélioration ou de mise en conformité.",
                        verbose_name="travaux depuis le dernier bail",
                    ),
                ),
                (
                    "honoraires_bail_bailleur",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        verbose_name="visite, dossier et bail : part bailleur (€ TTC)",
                    ),
                ),
                (
                    "honoraires_bail_locataire",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        verbose_name="visite, dossier et bail : part locataire (€ TTC)",
                    ),
                ),
                (
                    "honoraires_edl_bailleur",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        verbose_name="état des lieux : part bailleur (€ TTC)",
                    ),
                ),
                (
                    "honoraires_edl_locataire",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        verbose_name="état des lieux : part locataire (€ TTC)",
                    ),
                ),
                (
                    "conditions_particulieres",
                    models.TextField(
                        blank=True, verbose_name="autres conditions particulières"
                    ),
                ),
                (
                    "lieu_signature",
                    models.CharField(
                        default="Toulouse",
                        max_length=100,
                        verbose_name="lieu de signature",
                    ),
                ),
                (
                    "date_signature",
                    models.DateField(
                        blank=True, null=True, verbose_name="date de signature"
                    ),
                ),
                (
                    "date_fin_effective",
                    models.DateField(
                        blank=True,
                        help_text="Date de départ du locataire.",
                        null=True,
                        verbose_name="fin effective",
                    ),
                ),
                (
                    "fichier_signe",
                    models.FileField(
                        blank=True, upload_to="baux/", verbose_name="bail signé (scan)"
                    ),
                ),
                (
                    "bien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="baux",
                        to="biens.bien",
                    ),
                ),
                (
                    "mandat",
                    models.ForeignKey(
                        blank=True,
                        help_text="Mandat de gestion dont proviennent les honoraires.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="baux",
                        to="mandats.mandat",
                    ),
                ),
            ],
            options={
                "verbose_name": "bail",
                "verbose_name_plural": "baux",
                "ordering": ["-date_effet"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalBail",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="créé le"
                    ),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="modifié le"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("nu", "Logement nu"),
                            ("meuble", "Logement meublé"),
                            ("etudiant", "Logement meublé loué à un étudiant (9 mois)"),
                        ],
                        default="nu",
                        max_length=10,
                        verbose_name="type de bail",
                    ),
                ),
                (
                    "usage_mixte",
                    models.BooleanField(
                        default=False,
                        verbose_name="usage mixte professionnel et d'habitation",
                    ),
                ),
                (
                    "garant",
                    models.CharField(
                        blank=True,
                        help_text="Nom et adresse de la caution, le cas échéant.",
                        max_length=255,
                    ),
                ),
                ("date_effet", models.DateField(verbose_name="date de prise d'effet")),
                (
                    "loyer",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=9,
                        verbose_name="loyer mensuel hors charges (€)",
                    ),
                ),
                (
                    "mode_charges",
                    models.CharField(
                        choices=[
                            (
                                "provision",
                                "Provisions sur charges avec régularisation annuelle",
                            ),
                            ("forfait", "Forfait de charges"),
                        ],
                        default="provision",
                        max_length=10,
                        verbose_name="modalité des charges",
                    ),
                ),
                (
                    "charges",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        verbose_name="provision ou forfait de charges mensuel (€)",
                    ),
                ),
                (
                    "jour_paiement",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="jour de paiement"
                    ),
                ),
                (
                    "a_echoir",
                    models.BooleanField(
                        default=True, verbose_name="payable d'avance (à échoir)"
                    ),
                ),
                (
                    "depot_garantie",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        verbose_name="dépôt de garantie (€)",
                    ),
                ),
                (
                    "irl_trimestre",
                    models.CharField(
                        help_text="Par exemple « 2e trimestre 2026 ».",
                        max_length=30,
                        verbose_name="trimestre de référence de l'IRL",
                    ),
                ),
                (
                    "irl_valeur",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="valeur de l'IRL"
                    ),
                ),
                (
                    "precedent_loyer",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="À renseigner si le précédent locataire est parti depuis moins de 18 mois.",
                        max_digits=9,
                        null=True,
                        verbose_name="dernier loyer du précédent locataire (€)",
                    ),
                ),
                (
                    "precedent_date_versement",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="date de son dernier versement",
                    ),
                ),
                (
                    "precedent_date_revision",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="date de sa dernière révision",
                    ),
                ),
                (
                    "travaux",
                    models.TextField(
                        blank=True,
                        help_text="Montant et nature des travaux d'amélioration ou de mise en conformité.",
                        verbose_name="travaux depuis le dernier bail",
                    ),
                ),
                (
                    "honoraires_bail_bailleur",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        verbose_name="visite, dossier et bail : part bailleur (€ TTC)",
                    ),
                ),
                (
                    "honoraires_bail_locataire",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        verbose_name="visite, dossier et bail : part locataire (€ TTC)",
                    ),
                ),
                (
                    "honoraires_edl_bailleur",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        verbose_name="état des lieux : part bailleur (€ TTC)",
                    ),
                ),
                (
                    "honoraires_edl_locataire",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        verbose_name="état des lieux : part locataire (€ TTC)",
                    ),
                ),
                (
                    "conditions_particulieres",
                    models.TextField(
                        blank=True, verbose_name="autres conditions particulières"
                    ),
                ),
                (
                    "lieu_signature",
                    models.CharField(
                        default="Toulouse",
                        max_length=100,
                        verbose_name="lieu de signature",
                    ),
                ),
                (
                    "date_signature",
                    models.DateField(
                        blank=True, null=True, verbose_name="date de signature"
                    ),
                ),
                (
                    "date_fin_effective",
                    models.DateField(
                        blank=True,
                        help_text="Date de départ du locataire.",
                        null=True,
                        verbose_name="fin effective",
                    ),
                ),
                (
                    "fichier_signe",
                    models.TextField(
                        blank=True, max_length=100, verbose_name="bail signé (scan)"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "bien",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="biens.bien",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mandat",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Mandat de gestion dont proviennent les honoraires.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="mandats.mandat",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical bail",
                "verbose_name_plural": "historical baux",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLocataire",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "civilite",
                    models.CharField(
                        blank=True,
                        choices=[("M.", "Monsieur"), ("Mme", "Madame")],
                        max_length=5,
                        verbose_name="civilité",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100, verbose_name="prénom")),
                (
                    "date_naissance",
                    models.DateField(
                        blank=True, null=True, verbose_name="date de naissance"
                    ),
                ),
                (
                    "lieu_naissance",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="lieu de naissance"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="téléphone"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "bail",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="baux.bail",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical locataire",
                "verbose_name_plural": "historical locataires",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Locataire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "civilite",
                    models.CharField(
                        blank=True,
                        choices=[("M.", "Monsieur"), ("Mme", "Madame")],
                        max_length=5,
                        verbose_name="civilité",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100, verbose_name="prénom")),
                (
                    "date_naissance",
                    models.DateField(
                        blank=True, null=True, verbose_name="date de naissance"
                    ),
                ),
                (
                    "lieu_naissance",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="lieu de naissance"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="téléphone"
                    ),
                ),
                (
                    "bail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locataires",
                        to="baux.bail",
                    ),
                ),
            ],
            options={
                "verbose_name": "locataire",
                "ordering": ["pk"],
            },
        ),
    ]
