# Generated by Django 5.2.17 on 2026-10-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baux", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bail",
            name="colocation",
            field=models.BooleanField(
                default=False,
                help_text="Plusieurs locataires qui ne sont ni mariés ni pacsés ensemble.",
                verbose_name="colocation",
            ),
        ),
        migrations.AddField(
            model_name="historicalbail",
            name="colocation",
            field=models.BooleanField(
                default=False,
                help_text="Plusieurs locataires qui ne sont ni mariés ni pacsés ensemble.",
                verbose_name="colocation",
            ),
        ),
        migrations.AddField(
            model_name="historicallocataire",
            name="garant",
            field=models.CharField(
                blank=True,
                help_text="Nom et adresse de la caution de ce locataire, le cas échéant.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="locataire",
            name="garant",
            field=models.CharField(
                blank=True,
                help_text="Nom et adresse de la caution de ce locataire, le cas échéant.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="bail",
            name="garant",
            field=models.CharField(
                blank=True,
                help_text="Nom et adresse d'une caution qui garantit tous les locataires, le cas échéant.",
                max_length=255,
                verbose_name="garant commun",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbail",
            name="garant",
            field=models.CharField(
                blank=True,
                help_text="Nom et adresse d'une caution qui garantit tous les locataires, le cas échéant.",
                max_length=255,
                verbose_name="garant commun",
            ),
        ),
    ]
