# Generated by Django 5.2.17 on 2026-10-03 23:49

import candidatures.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("baux", "0001_initial"),
        ("biens", "0003_identifiant_fiscal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cree_le",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "modifie_le",
                    models.DateTimeField(auto_now=True, verbose_name="modifié le"),
                ),
                (
                    "lien_dossierfacile",
                    models.URLField(
                        blank=True,
                        help_text="Lien de partage envoyé par le candidat.",
                        validators=[candidatures.models.valider_lien_dossierfacile],
                        verbose_name="lien DossierFacile",
                    ),
                ),
                (
                    "dossier_verifie",
                    models.BooleanField(
                        default=False,
                        help_text="Cocher une fois le dossier ouvert et les pièces vérifiées.",
                        verbose_name="dossier consulté sur DossierFacile",
                    ),
                ),
                (
                    "garantie",
                    models.CharField(
                        choices=[
                            ("aucune", "Aucune"),
                            ("personne", "Caution personne physique"),
                            ("visale", "Visale"),
                            ("autre", "Autre garantie"),
                        ],
                        default="aucune",
                        max_length=10,
                    ),
                ),
                (
                    "date_entree_souhaitee",
                    models.DateField(
                        blank=True, null=True, verbose_name="entrée souhaitée"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Jamais communiquées au candidat. Ne pas y noter de critère interdit.",
                        verbose_name="notes internes",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("a_etudier", "À étudier"),
                            ("retenue", "Retenue"),
                            ("non_retenue", "Non retenue"),
                            ("desistement", "Désistement du candidat"),
                        ],
                        default="a_etudier",
                        max_length=12,
                    ),
                ),
                (
                    "decide_le",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="décidé le"
                    ),
                ),
                (
                    "refus_envoye_le",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="réponse envoyée le"
                    ),
                ),
                (
                    "bail",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidature",
                        to="baux.bail",
                    ),
                ),
                (
                    "bien",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidatures",
                        to="biens.bien",
                    ),
                ),
                (
                    "decide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="décidé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "candidature",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="Candidat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "civilite",
                    models.CharField(
                        blank=True,
                        choices=[("M.", "Monsieur"), ("Mme", "Madame")],
                        max_length=5,
                        verbose_name="civilité",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100, verbose_name="prénom")),
                (
                    "date_naissance",
                    models.DateField(
                        blank=True, null=True, verbose_name="date de naissance"
                    ),
                ),
                (
                    "lieu_naissance",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="lieu de naissance"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="téléphone"
                    ),
                ),
                ("profession", models.CharField(blank=True, max_length=100)),
                ("employeur", models.CharField(blank=True, max_length=150)),
                (
                    "contrat",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cdi", "CDI"),
                            ("cdd", "CDD"),
                            ("interim", "Intérim"),
                            ("independant", "Indépendant"),
                            ("fonctionnaire", "Fonctionnaire"),
                            ("etudiant", "Étudiant"),
                            ("apprenti", "Apprenti"),
                            ("retraite", "Retraité"),
                            ("autre", "Autre"),
                        ],
                        max_length=15,
                        verbose_name="type de contrat",
                    ),
                ),
                (
                    "date_embauche",
                    models.DateField(
                        blank=True, null=True, verbose_name="date d'embauche"
                    ),
                ),
                (
                    "revenus_mensuels",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=9,
                        null=True,
                        verbose_name="revenus mensuels nets (€)",
                    ),
                ),
                (
                    "candidature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidats",
                        to="candidatures.candidature",
                    ),
                ),
            ],
            options={
                "verbose_name": "candidat",
                "ordering": ["pk"],
            },
        ),
    ]
