# Generated by Django 5.2.17 on 2026-10-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidatures", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidature",
            name="jeton",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="candidature",
            name="lien_cree_le",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="lien envoyé le"
            ),
        ),
        migrations.AddField(
            model_name="candidature",
            name="rempli_le",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="rempli par le locataire le"
            ),
        ),
    ]
