# Generated by Django 5.2.17 on 2026-10-04 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidatures", "0002_lien_locataire"),
    ]

    operations = [
        migrations.CreateModel(
            name="Garant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "civilite",
                    models.CharField(
                        blank=True,
                        choices=[("M.", "Monsieur"), ("Mme", "Madame")],
                        max_length=5,
                        verbose_name="civilité",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100, verbose_name="prénom")),
                (
                    "adresse",
                    models.CharField(
                        help_text="Rue, code postal et ville.",
                        max_length=255,
                        verbose_name="adresse complète",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="téléphone"
                    ),
                ),
                (
                    "candidat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="garants",
                        to="candidatures.candidat",
                    ),
                ),
            ],
            options={
                "verbose_name": "garant",
                "ordering": ["pk"],
            },
        ),
    ]
