# Generated by Django 5.2.18 on 2026-10-10 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0003_garants'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='nombre_locataires',
            field=models.PositiveSmallIntegerField(default=1, help_text='Colocataires ou couple : le formulaire envoyé au candidat demande les informations de chacun.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='nombre de locataires'),
        ),
    ]
